export const trends = [
    { id: 0, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 1, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 2, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 3, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 4, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 5, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 6, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 7, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 8, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 9, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 10, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 11, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 12, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 13, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 14, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
    { id: 15, heading:'maneth', des:'jsihbeikuwhdikhihsyjskef', img:'./Logo1.png'},
]